FROM --platform=$BUILDPLATFORM golang:1.19.2 as builder

WORKDIR /oldgeneral

COPY . .

RUN go mod tidy

ARG TARGETOS
ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a -o /output/api cmd/api/api.go

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /output/api api

# Command to run the executable
USER 65532:65532
ENTRYPOINT ["/api"]
