FROM --platform=$BUILDPLATFORM golang:1.20.2 as builder

WORKDIR /oldgeneral

COPY . .

RUN go mod download -x

ARG TARGETOS
ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a -o /output/user cmd/user/user.go

FROM gcr.io/distroless/static-debian11
WORKDIR /
COPY --from=builder /output/user user

# Command to run the executable
USER 65532:65532
ENTRYPOINT ["/user"]
