// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	UserID    string `gorm:"column:user_id;not null" json:"user_id"`
	SigninID  string `gorm:"column:signin_id;not null" json:"signin_id"`
	Content   string `gorm:"column:content;not null" json:"content"`
	CreatedAt int64  `gorm:"column:created_at" json:"created_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
