// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProp = "props"

// Prop mapped from table <props>
type Prop struct {
	ID     string `gorm:"column:id;primaryKey" json:"id"`
	FlagID string `gorm:"column:flag_id;not null" json:"flag_id"`
	Type   int32  `gorm:"column:type;not null" json:"type"`
	UseAt  int64  `gorm:"column:use_at" json:"use_at"`
}

// TableName Prop's table name
func (*Prop) TableName() string {
	return TableNameProp
}
