// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSiege = "siege"

// Siege mapped from table <siege>
type Siege struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	UserID    string `gorm:"column:user_id;not null" json:"user_id"`
	FlagID    string `gorm:"column:flag_id;not null" json:"flag_id"`
	CreatedAt int64  `gorm:"column:created_at" json:"created_at"`
}

// TableName Siege's table name
func (*Siege) TableName() string {
	return TableNameSiege
}
