// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSignIn = "sign_in"

// SignIn mapped from table <sign_in>
type SignIn struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	FlagID      string `gorm:"column:flag_id;not null" json:"flag_id"`
	UserID      string `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt   int64  `gorm:"column:created_at" json:"created_at"`
	CurrentTime int32  `gorm:"column:current_time;not null" json:"current_time"`
	TotalTime   int32  `gorm:"column:total_time;not null" json:"total_time"`
	Content     string `gorm:"column:content;not null" json:"content"`
	PictureURL  string `gorm:"column:picture_url;not null" json:"picture_url"`
}

// TableName SignIn's table name
func (*SignIn) TableName() string {
	return TableNameSignIn
}
