// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVip = "vip"

// Vip mapped from table <vip>
type Vip struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	UserID    string `gorm:"column:user_id;not null" json:"user_id"`
	StartTime int64  `gorm:"column:start_time" json:"start_time"`
	EndTime   int64  `gorm:"column:end_time" json:"end_time"`
}

// TableName Vip's table name
func (*Vip) TableName() string {
	return TableNameVip
}
