// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWallet = "wallet"

// Wallet mapped from table <wallet>
type Wallet struct {
	ID      string `gorm:"column:id;primaryKey" json:"id"`
	UserID  string `gorm:"column:user_id;not null" json:"user_id"`
	GoldNum int64  `gorm:"column:gold_num;not null" json:"gold_num"`
}

// TableName Wallet's table name
func (*Wallet) TableName() string {
	return TableNameWallet
}
