// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWaterFlow = "water_flow"

// WaterFlow mapped from table <water_flow>
type WaterFlow struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	UserID    string `gorm:"column:user_id;not null" json:"user_id"`
	GoldNum   int64  `gorm:"column:gold_num;not null" json:"gold_num"`
	CreatedAt int64  `gorm:"column:created_at" json:"created_at"`
	Content   string `gorm:"column:content;not null" json:"content"`
}

// TableName WaterFlow's table name
func (*WaterFlow) TableName() string {
	return TableNameWaterFlow
}
